# Generated by Django 4.2.17 on 2024-12-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_event_team_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
